### ISSUE TITLE
Termux error

### ISSUE THREAD

**Issue by bmvaghera** [IAmBlackHacker/Facebook-BruteForce#3]
Mengambil 3 id teman
Traceback (most recent call last):
  File "MBF2.pye", line 1, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 407, in <module>
  File "<script>", line 400, in menu
  File "<script>", line 339, in idteman
NameError: global name 'id_teman' is not defined

**Comment by IAmBlackHacker** [comment]
> Mengambil 3 id teman
> Traceback (most recent call last):
> File "MBF2.pye", line 1, in 
> File "<script>", line 12, in 
> File "<script>", line 12, in 
> File "<script>", line 407, in 
> File "<script>", line 400, in menu
> File "<script>", line 339, in idteman
> NameError: global name 'id_teman' is not defined

You Are Using Wrong File (Execute Right File after installing all requirements).

**Comment by jasmineramona** [comment]
Contact jasmineramona@protonmail.com if you need facebook hacking help
